name: User Request
description: Request a new task in the IOOS Marine Life Data Network
title: "User Request: "
body:
  - type: markdown
    attributes:
      value: To submit a user request to the IOOS Marine Life Data Network, please feel out the issue template below.
  - type: input
    id: who
    attributes:
      label: Who is requesting this?
  - type: textarea
    id: what
    attributes:
      label: What is being requested?
  - type: textarea
    id: why
    attributes:
      label: How would this request improve your current workflow?
  - type: input
    id: contact
    attributes:
      label: How can we get in contact with you to follow up on this request?
